const boardModel = {
    boardIdx: 0,
    userIdx: 0,
    channelType: "",
    importantType: "",
    boardType: "",
    processStatus: "",
    detailType: "",
    categoryType: "",
    subject: "",
    subTitle: "",
    content: "",
    securityCode: "",
    showYn: "Y",
    openYn: "Y",
    boardPwd: "",
    alimYn: "",
    userNameFirstKo: "",
    userNameLastKo: "",
    userNameFirstEn: "",
    userNameLastEn: "",
    localYn: "",
    email: "",
    gender: "",
    birthYyyy: "",
    birthMm: "",
    birthDd: "",
    interPhoneNumber: "",
    mobile1: "",
    mobile2: "",
    mobile3: "",
    mobileAgency: "",
    // attachmentFile: [{}],
    fileContent: "",
    // useYn: "",
    // delYn: "",
    userNameKo: "",
    userNameEn: "",
    regUserIdx: 0,
    regUserNameKo: "",
    regUserNameEn: "",
    // regDttm: "",
    modUserIdx: 0,
    modUserNameKo: "",
    modUserNameEn: "",
    modDttm: "",
};

export { boardModel };
